// Flint Reactivity — Fine-grained signals system v4

export {
  state,
  computed,
  effect,
  watch,
  flushSync,
  untrack,
  captureScope,
  createSelector,
  createRoot,
  onCleanup,
  // NEW v4 simplified APIs
  reactive,
  model,
  bind,
  createRef,
  shallowRef,
  derive,
  signals,
  poll,
  watchDebounced,
  watchThrottled,
  computedSet,
} from './signals.js'
export type {
  Signal,
  Computed,
  Effect,
  CleanupFn,
  Selector,
  Scope,
  ReactiveProxy,
  Ref,
  Writable,
  Readable,
  WatchHandle,
} from './types.js'

// Debug mode v2
export {
  DebugManager,
  createDebugManager,
  getDebugManager,
  enableDebug,
  disableDebug,
  trackSignal,
  trackComputed,
  printSignalHistory,
  printComputedStats,
  printPerformanceSummary,
} from './debug.js'
export type {
  DebugOptions,
  SignalDebugInfo,
  ComputedDebugInfo,
  EffectDebugInfo,
  SignalHistoryEntry,
} from './debug.js'

// Type Helpers (v4.1)
export type {
  InferSignal,
  InferComputed,
  InferWritable,
  InferReadable,
  ComponentProps,
  ComponentReturn,
  PartialExcept,
  RequiredExcept,
  InferFormValues,
  InferFormErrors,
  Validator,
  Validators,
  InferStoreState,
  InferStoreActions,
  Nullable,
  Optional,
  Maybe,
  DeepReadonly,
  DeepMutable,
  FunctionKeys,
  NonFunctionKeys,
  PickFunctions,
  PickState,
  MethodParams,
  MethodReturns,
  EventHandler,
  EventHandlers,
  UnwrapPromise,
  Async,
  Await,
  ArrayElement,
  Tuple,
  TupleOf,
  CamelCase,
  KebabCase,
  If,
  And,
  Or,
  Not,
  Equals,
  IsNever,
  IsAny,
  IsUnknown,
} from './types-helpers.js'

// Solid/React Compatibility Aliases (v4.2)
export {
  createSignal,
  createEffect,
  createMemo,
  createStore,
  batch,
  createResource,
  from,
  produce,
} from './compat.js'
